version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: agent-api
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
      - DB_NAME=database
      - DB_HOST=postgres
      - DB_PORT=5432
      - SECRET_KEY=dc76ad3137c861a8a4cf15b4284eca902be7485a81af89b84769f93050a8febd
      - GRAPHHOPPER_KEY=41b99b2f-0843-4ccc-947b-89ef6cefade4
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090




