"""add is cancel

Revision ID: 34e167aef484
Revises: 2669e30dc68f
Create Date: 2024-03-31 22:31:32.182972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e167aef484'
down_revision: Union[str, None] = '2669e30dc68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('is_canceled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'is_canceled')
    # ### end Alembic commands ###
