"""add routes

Revision ID: 812baf822c23
Revises: 34e167aef484
Create Date: 2024-04-01 13:50:57.750736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812baf822c23'
down_revision: Union[str, None] = '34e167aef484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
                    sa.Column('id', sa.BIGINT(),
                              autoincrement=True, nullable=False),
                    sa.Column('agent_id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('locations', sa.JSON(), nullable=False),
                    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
